// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgkirlrztoolcsyiluvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNna2lybHJ6dG9vbGNzeWlsdXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzgwMjAsImV4cCI6MjA3MjQxNDAyMH0.gsZnwUMYdINzyJpBu1aBZrpgsSNz1rciu5deBm9j5Mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});